
branches:
  only:
    - master

services:
  - docker

before_install:
  # Upgrade Docker to the latest version
  - docker version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version
  - docker-compose --version

  - sudo apt-get install npm

script:
  - make test
